version: '3.3'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: producer_db
    ports:
      - "3306:3306"
    networks:
      - microservices-network

  eureka-server:
    image: rajeshmandala/eureka-image  # Pulling from Docker Hub
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  producer-app:
    build: .
    container_name: producer-app
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://34.229.78.152:3306/producer_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://34.229.78.152:8761/eureka
    ports:
      - "4043:4043"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
